### ISSUE TITLE
[EXTRA] MoSCoW

### ISSUE THREAD

**Issue by CADU110** [UnBArqDsw2024-2/2024.2_G6_Agenda_Entrega_02#23]
# Atividade: Artefato de MoSCoW

## Descrição

Esta issue tem como objetivo organizar a criação do MoSCoW para o projeto e desenvolver o artefato no Docsify. O artefato deverá conter:

1. Introdução explicando o que é o (nome do artefato).
2. Resultados da modelagem com uma breve análise.
3. Explicação detalhada do diagrama montado.
4. Referências utilizadas.
5. Histórico de versões do artefato.

## Tarefas

1. **Desenvolvimento do (nome do artefato)**
   - [ ] Desenvolver o MoSCoW conforme especificações.
   
2. **Documentação no Docsify**
   - [ ] Introdução: Definir o que é, o propósito do artefato;
   - [ ] Resultados: Apresentar o principal, a modelagem, a tarefa que foi executada.
   - [ ] Explicação: Descrever por escrito brevemente esse resultado.
   - [ ] Referências: Incluir as fontes e materiais utilizados.
   - [ ] Histórico de Versão: Registrar todas as versões, autores e modificações feitas no artefato.

## Responsabilidades

| Responsável   | Tarefa                                    |
|---------------|------------------------------------------|
| Todos      | Desenvolvimento do MoSCoW  |

> **Nota:** Cada responsável deve revisar seu trabalho e garantir que está formatado corretamente no MkDocs.

## Critérios de Sucesso

Sua lista é um bom começo, mas podemos torná-la mais robusta e acionável.  Aqui estão alguns critérios de aceitação aprimorados para validar sua priorização MoSCoW:

## Must Have (M)

- [ ] **Impacto Severo**: A ausência de QUALQUER requisito "Must Have" tornaria o produto inutilizável, inviável ou inseguro, impedindo o lançamento ou causando falha crítica. Justifique cada "M" com o impacto da sua ausência.
- [ ] **Valor Essencial**: Cada requisito "Must Have" entrega valor comercial fundamental e é absolutamente essencial para atingir os objetivos principais do projeto. Descreva o valor de cada "M".
- [ ] **Teste de Falha**: Simule a ausência de cada "M" para confirmar o impacto severo. Documente os resultados.

## Should Have (S)

- [ ] **Alto Valor**: Cada requisito "Should Have" adiciona valor significativo, melhora a experiência do usuário ou reduz riscos importantes. Quantifique o valor sempre que possível (ex: aumento de conversão, redução de suporte).
- [ ] **Impacto Mensurável**: A ausência de um "S" tem um impacto negativo perceptível, mas não impede o lançamento. Defina como medir esse impacto.
- [ ] **Aceitação de Risco Consciente**: Se um "S" for removido, o risco associado deve ser explicitamente aceito e documentado pelas partes interessadas.

## Could Have (C)

- [ ] **Valor Incremental**: Cada requisito "Could Have" oferece melhorias ou benefícios adicionais, mas não é essencial para o lançamento. Descreva o benefício incremental.
- [ ] **Adiável/Descartável**: Confirme que cada "C" pode ser adiado para uma versão futura ou completamente descartado sem impactar significativamente os objetivos do projeto.
- [ ] **Baixo Custo de Implementação (Relativo)**: Idealmente, os "Could Haves" devem ter um custo de implementação relativamente baixo em comparação com o valor que agregam.

## Won't Have (W - This Time)

- [ ] **Fora do Escopo**: Cada requisito "Won't Have" está claramente fora do escopo do projeto atual e não será considerado nesta iteração/release.
- [ ] **Justificativa Documentada**: A razão para adiar ou rejeitar cada "W" deve ser documentada para referência futura. Pode ser útil categorizar os "W" (ex: futuro, rejeitado, etc.).

## Geral

- [ ] **Sem Duplicatas**: Verifique se não há requisitos duplicados em nenhuma das categorias.
- [ ] **Requisitos Claros e Concisos**: Todos os requisitos são escritos de forma clara, concisa, inequívoca e fácil de entender por todas as partes interessadas.
- [ ] **Alinhamento com a Visão**: A priorização MoSCoW está alinhada com a visão geral do produto e a estratégia de roadmap.

Ao utilizar estes critérios de aceitação, você garante uma priorização MoSCoW mais robusta, justificada e menos suscetível a erros, resultando em um desenvolvimento mais eficiente e focado no que realmente importa.

## Observações

- Use o estilo e o formato já definido no Docsify para manter a consistência do projeto.
- Certifique-se de que todas as fontes e referências são devidamente citadas.

> Lembrem-se de atualizar esta issue conforme as tarefas forem sendo concluídas!

**Comment by vitorfleonardo** [comment]
terminamos
