### ISSUE TITLE
[EXTRA] i*

### ISSUE THREAD

**Issue by yagompassos** [UnBArqDsw2024-2/2024.2_G6_Agenda_Entrega_02#40]
# Atividade: Artefato de i*

## Descrição

Esta issue tem como objetivo organizar a criação do i star para o projeto e desenvolver o artefato no Docsify. O artefato deverá conter:

1. Introdução explicando o que é o i star.
2. Resultados da modelagem com uma breve análise.
3. Explicação detalhada do diagrama montado.
4. Referências utilizadas.
5. Histórico de versões do artefato.

## Tarefas

1. **Desenvolvimento do (nome do artefato)**
   - [ ] Desenvolver o (nome do artefato) conforme especificações da orientações WIKI da professora.
   
2. **Documentação no Docsify**
   - [ ] Introdução: Definir o que é, o propósito do artefato;
   - [ ] Resultados: Apresentar o principal, a modelagem, a tarefa que foi executada.
   - [ ] Explicação: Descrever por escrito brevemente esse resultado.
   - [ ] Referências: Incluir as fontes e materiais utilizados.
   - [ ] Histórico de Versão: Registrar todas as versões, autores e modificações feitas no artefato.

## Responsabilidades

| Responsável   | Tarefa                                    |
|---------------|------------------------------------------|
|  Yago     | Desenvolvimento do corpo e texto do artefato. Diagramação|
|  Hugo    | Trazer referências para o desenvolvimento. Diagramação |

> **Nota:** Cada responsável deve revisar seu trabalho e garantir que está formatado corretamente no MkDocs.

## Critérios de Sucesso

- [ ] O mapeamento deve corresponder com as funcionalidades da agenda
- [ ] Deve ser utilizado o [modelo SD](https://en.wikipedia.org/wiki/I*) de diagramação i*
- [ ] O artefato deve estar padronizado de acordo com as normas definidas pelo grupo
- [ ] O artefato deve ser revisado

## Observações

- Use o estilo e o formato já definido no Docsify para manter a consistência do projeto.
- Certifique-se de que todas as fontes e referências são devidamente citadas.

> Lembrem-se de atualizar esta issue conforme as tarefas forem sendo concluídas!

**Comment by vitorfleonardo** [comment]
Não deu tempo e não será feita no tempo hábil desta entrega
